print('-------------------------------------')
print('       Operações Matemáticas         ')
print('-------------------------------------')
a=input('Digite o Primeiro Número: ')
b=input('Digite o Segundo Número:  ')
soma=int(a) + int(b)
subtra= int(a) - int(b)
multi= int(a) * int(b)
divi= int(a) / int(b)
float(divi)
print('-------------------------------------')
print('         Resultado Final             ')
print('-------------------------------------')
print('O Resultado da Soma é:',soma)
print('O Resultado da Subtração é:',subtra)
print('O Resultado da Multiplicação é:',multi)
print('O Resultado da Divisão é:',divi)